### ISSUE TITLE
请问下翻译的英文版本能提供吗？

### ISSUE THREAD

**Issue by lhtin** [Jason2013/boc-chinese-text#8]
另外我打算翻译一些全局优化的章节，如果不介意的话。

**Comment by Jason2013** [comment]
英文原版及书中图片资源：
https://pan.baidu.com/s/1xpigYSe2qKqHf3pPu7H-0A?pwd=imvb

欢迎共同翻译。

**Comment by lhtin** [comment]
好的感谢
